stages:
  - build
  - infrastructure-update

complex_build_job:
  stage: build
  script:
    - echo "pulumi rocks!"
  only:
    - develop

pulumi:
  stage: infrastructure-update
  before_script:
    - chmod +x ./scripts/*.sh
    - ./scripts/setup.sh
  script:
    - ./scripts/run-pulumi.sh
  only:
    - develop
